# -*- coding: utf-8 -*-
"""praktikum.algo.pakanung.modul7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvPAMC6Uld1B0McX5ejqVQWbmGiuXbSR
"""

#praktikum algo pak anung modul 7
#menentukan bilang prima
#faradina kusuma, 065002500035
#13 september 2025
#latihan 1

def cek_prima(x):
    if x <= 1:
        return False
    if x == 2:
        return True
    for i in range(2,x):
      if x % i == 0:
        return False
    return True

def tampil_hasil_prima(angka, status_prima):
    if status_prima:
        print(angka, "adalah bilangan prima")
    else:
        print(angka, "bukan bilangan prima")

angka_input = int(input("Masukkan angka: "))
status_prima = cek_prima(angka_input)
tampil_hasil_prima(angka_input, status_prima)

#latihan 2

def dapatkan_akhiran_ordinal(n):
    if n == 0:
        return 'th'

    dua_digit_akhir = n % 100
    if 10 <= dua_digit_akhir <= 20:
        return 'th' #maksudnya akhir -1,-2,-3

    digit_akhir = n % 10
    if digit_akhir == 1:
        return 'st'
    elif digit_akhir == 2:
        return 'nd'
    elif digit_akhir == 3:
        return 'rd'
    else:
        return 'th'

print("ordinal Number")
print("ketik 0 untuk menghentikan program")

while True:
    input_str = input("masukkan angka: ")
    try:
        angka = int(input_str)
    except ValueError:
        print("Input tidak valid. Harap masukkan angka.")
        continue

    if angka == 0:
        print("(0,'th')")
        print("terima kasih sudah menggunakan program saya")
        break
    else:
        suffix = dapatkan_akhiran_ordinal(angka)
        print(f"({angka},'{suffix}')")